In [1]:
import pandas as pd
import numpy as np

In [2]:
train_df = pd.read_csv('train_df.csv')
train_df.head()

Call_Me?  Money  Target
0      Yes      5      10
1       No      3       4
2    Maybe      5       5
3      Yes     10       7
4      Yes      9       9

In [3]:
X = train_df.drop(columns=['Target'])
y = train_df['Target']

categorical_columns = ['Call_Me?']
continuous_columns = ['Money']

_X_dummy = pd.get_dummies(data = X,
                         columns = categorical_columns)

from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(_X_dummy, y)
linreg.predict(_X_dummy)

array([10.16666667,  4.        ,  5.        ,  7.66666667,  8.16666667])

In [4]:
test_df = pd.read_csv('test_df.csv')
test_df.head()

Call_Me?  Money
0      Yes      5
1      Yes      2
2      Yes      3
3      Yes      6
4       No      1

In [5]:
categorical_columns = ['Call_Me?']
continuous_columns = ['Money']

_test_dummy = pd.get_dummies(data = test_df,
                            columns = categorical_columns)
linreg.predict(_test_dummy)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [6]:
_X_dummy

Money  Call_Me?_Maybe  Call_Me?_No  Call_Me?_Yes
0      5               0            0             1
1      3               0            1             0
2      5               1            0             0
3     10               0            0             1
4      9               0            0             1

In [7]:
_test_dummy

Money  Call_Me?_No  Call_Me?_Yes
0      5            0             1
1      2            0             1
2      3            0             1
3      6            0             1
4      1            1             0

In [8]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(handle_unknown='ignore')

X = train_df.drop(columns='Target')
y = train_df['Target']

continuous_columns = ['Money']
categorical_columns = ['Call_Me?']

_train_ohe = ohe.fit_transform(X[categorical_columns]).toarray()
_train_ohe_df = pd.DataFrame(data = _train_ohe, 
                             columns = ohe.get_feature_names(categorical_columns))

_X_merged = X[continuous_columns].merge(_train_ohe_df, left_index=True, right_index=True)
_X_merged

Money  Call_Me?_Maybe  Call_Me?_No  Call_Me?_Yes
0      5             0.0          0.0           1.0
1      3             0.0          1.0           0.0
2      5             1.0          0.0           0.0
3     10             0.0          0.0           1.0
4      9             0.0          0.0           1.0

In [9]:
linreg = LinearRegression()
linreg.fit(_X_merged, y)
linreg.predict(_X_merged)

array([10.16666667,  4.        ,  5.        ,  7.66666667,  8.16666667])

In [10]:
categorical_columns = ['Call_Me?']
continuous_columns = ['Money']

_test_ohe = ohe.transform(test_df[categorical_columns]).toarray()
_test_ohe_df = pd.DataFrame(data = _test_ohe, 
                            columns = ohe.get_feature_names(categorical_columns))


_test_merged = test_df[continuous_columns].merge(_test_ohe_df, left_index=True, right_index=True)
_test_merged

Money  Call_Me?_Maybe  Call_Me?_No  Call_Me?_Yes
0      5             0.0          0.0           1.0
1      2             0.0          0.0           1.0
2      3             0.0          0.0           1.0
3      6             0.0          0.0           1.0
4      1             0.0          1.0           0.0

In [11]:
linreg.predict(_test_merged)

array([10.16666667, 11.66666667, 11.16666667,  9.66666667,  5.        ])

In [12]:
ohe.categories_

[array(['Maybe', 'No', 'Yes'], dtype=object)]